/**
 * The wire-ABI prelude — the 28 bytes that open every client connection, in both directions,
 * ahead of any bincode.
 *
 * ## Why it exists
 *
 * `PROTOCOL_VERSION` is not a layout identifier. herdr-mx and upstream/master both shipped `20`
 * while disagreeing on the tags this codec lives on (`ServerMessage::Terminal` 13 vs 2,
 * `ClientLaunchMode::TerminalAttach` 1 vs 2 — `mobile/.prd/03-blockers.md` B1), so a version match
 * proves nothing and `assertWelcomeAccepted` was always going to pass against the wrong peer.
 *
 * ## Why it is a prelude and not a field of `Welcome`
 *
 * The first value the forks disagree on, `ClientLaunchMode`, is a **field of `Hello`**, and the
 * side that decodes `Hello` is the *server*. A fingerprint carried in the server's `Welcome` would
 * be compared only after the server had already mis-parsed our handshake. So the identity goes in
 * front of everything: `src/protocol/abi.rs` on the Rust side reads it before it touches bincode,
 * and this file writes it before {@link encodeHelloFrame} goes out.
 *
 * ## What this does to {@link WireLayoutProbe}
 *
 * The probe was an *inference* — repeated undecodable tags with no `Terminal` behind them — and
 * said so in its own doc comment, naming this gate as the real fix. That fix is now here, so the
 * probe is demoted to a backstop for the case the prelude cannot cover: a peer that announces this
 * exact ABI and then behaves differently anyway. It is kept, not deleted, because the prelude is a
 * *claim* and the probe watches *behaviour*.
 *
 * ## Provenance
 *
 * Every constant below is transcribed from the mx tree, exactly like the tags in `constants.ts`,
 * and cross-checked byte-for-byte against the generated corpus by `test/fixtures.test.ts` — which
 * is generated from `WirePrelude::local().encode()` and therefore cannot drift from the server.
 *
 * Sources (herdr repo root):
 *   src/protocol/abi.rs  WIRE_ABI_MAGIC / WIRE_ABI_FORK / WIRE_ABI_EPOCH
 *   src/protocol/abi.rs  WIRE_SCHEMA_FINGERPRINT / accepted_wire_abis()
 *   docs/next/protocol/fixtures.json  vector `wire_abi_prelude` (the generated bytes)
 *   docs/next/protocol/abi-history.json  why each accepted ABI is accepted
 */
import { PROTOCOL_VERSION } from "./constants.js";
import { AbiMismatchError, type WirePreludeSummary } from "./errors.js";

/**
 * `src/protocol/abi.rs` `WIRE_ABI_MAGIC` — ASCII `HRDR`.
 *
 * Read as a little-endian `u32` this is 1_380_208_712, above *both* frame caps
 * ({@link RUST_MAX_FRAME_SIZE} 2 MiB and {@link RUST_MAX_GRAPHICS_FRAME_SIZE} 32 MiB), so it can
 * never be mistaken for a legal frame length prefix. That is what makes "does this stream start
 * with a prelude" a decision instead of a guess, in both directions.
 *
 * Not `Object.freeze`d: freezing a typed array throws in every engine
 * ("Cannot freeze array buffer views with elements"). It is never written to.
 */
export const WIRE_ABI_MAGIC: Uint8Array = new Uint8Array([0x48, 0x52, 0x44, 0x52]);

/** `src/protocol/abi.rs` `WIRE_ABI_FORK` — ASCII `herdr-mx`, fixed 8 bytes. */
export const WIRE_ABI_FORK = "herdr-mx";

/**
 * `src/protocol/abi.rs` `WIRE_ABI_EPOCH`.
 *
 * Epoch 2: `ClientMessage::RetargetTerminal` was appended at tag 14 (M6/B6), so the set of
 * messages a peer may legally send grew and the schema fingerprint moved with it. No existing tag
 * or payload changed, and `PROTOCOL_VERSION` deliberately stayed at 21 — the handshake's bytes are
 * identical. The decision and its user impact are `docs/next/protocol/abi-history.json`.
 *
 * Epoch 3: the upstream v0.8.2 merge. Six upstream variants landed at the two enum **tails**
 * (`ClientMessage` 15-17, `ServerMessage` 15-17), `ClientLaunchMode::AppDirectGraphics` was moved
 * to that enum's tail so `TerminalAttach` keeps tag 1, and `ServerMessage::MouseCapture` gained a
 * trailing `sgr_pixels: boolean`. **Nothing this codec encodes or decodes moved** — `Hello`,
 * `Welcome`, `Terminal` (13), `ObserveTerminal` (12) and `RetargetTerminal` (14) are byte-identical
 * — which is why only the fingerprint below had to be re-transcribed.
 */
export const WIRE_ABI_EPOCH = 3;

/**
 * `src/protocol/abi.rs` `WIRE_SCHEMA_FINGERPRINT`, hex.
 *
 * A sha256 prefix over the encodings of an exemplar of every `ClientMessage`/`ServerMessage`
 * variant. This codec cannot compute it — it has no Rust types to hash — so it is transcribed, and
 * `test/fixtures.test.ts` fails if the generated corpus disagrees. That is the same contract the
 * enum tags in `constants.ts` already live under.
 */
export const WIRE_SCHEMA_FINGERPRINT = "14e847ff6ae1d9f2";

/** `magic(4) + fork(8) + abi_epoch(u32LE) + protocol_version(u32LE) + schema_fingerprint(8)`. */
export const WIRE_ABI_PRELUDE_LEN = 28;

/** One peer wire ABI: the triple that identifies a byte layout. */
export interface WireAbi {
  protocolVersion: number;
  abiEpoch: number;
  schemaFingerprint: string;
}

/** What a peer announced about itself. Structurally {@link WirePreludeSummary}. */
export interface WirePrelude extends WireAbi, WirePreludeSummary {
  fork: string;
}

/** The ABI this codec speaks. */
export const LOCAL_WIRE_ABI: Readonly<WireAbi> = Object.freeze({
  protocolVersion: PROTOCOL_VERSION,
  abiEpoch: WIRE_ABI_EPOCH,
  schemaFingerprint: WIRE_SCHEMA_FINGERPRINT,
});

/**
 * The compatibility window — an explicit table, not `MIN..=CURRENT`.
 *
 * A range over versions cannot express the thing that actually breaks, because two forks shipped
 * the same version with different layouts. Mirrors `abi::accepted_wire_abis()`; every row and the
 * reason for it is recorded in `docs/next/protocol/abi-history.json`.
 *
 * One row today, and that is a decision: the only older peers that exist are pre-prelude builds,
 * which announce nothing at all and so cannot be told apart from upstream.
 */
export const ACCEPTED_WIRE_ABIS: ReadonlyArray<Readonly<WireAbi>> = Object.freeze([LOCAL_WIRE_ABI]);

const HEX = "0123456789abcdef";

function toHex(bytes: Uint8Array): string {
  let out = "";
  for (const byte of bytes) {
    out += HEX[(byte >> 4) & 0xf];
    out += HEX[byte & 0xf];
  }
  return out;
}

function fromHex(hex: string): Uint8Array {
  if (hex.length % 2 !== 0) {
    throw new Error(`hex string has an odd length: ${hex.length}`);
  }
  const out = new Uint8Array(hex.length / 2);
  for (let index = 0; index < out.length; index += 1) {
    const byte = Number.parseInt(hex.slice(index * 2, index * 2 + 2), 16);
    if (!Number.isInteger(byte)) {
      throw new Error(`invalid hex at offset ${index * 2}: ${hex}`);
    }
    out[index] = byte;
  }
  return out;
}

/** ASCII only; the fork name is a fixed 8-byte ASCII field by construction. */
function writeAscii(target: Uint8Array, offset: number, text: string, width: number): void {
  for (let index = 0; index < width; index += 1) {
    const code = index < text.length ? text.charCodeAt(index) : 0;
    if (code > 0x7f) {
      throw new Error(`wire-ABI fork name must be ASCII, got ${JSON.stringify(text)}`);
    }
    target[offset + index] = code;
  }
}

function readAscii(source: Uint8Array, offset: number, width: number): string {
  let out = "";
  for (let index = 0; index < width; index += 1) {
    const code = source[offset + index] ?? 0;
    if (code === 0) {
      continue;
    }
    out += String.fromCharCode(code);
  }
  return out;
}

function writeU32Le(target: Uint8Array, offset: number, value: number): void {
  target[offset] = value & 0xff;
  target[offset + 1] = (value >>> 8) & 0xff;
  target[offset + 2] = (value >>> 16) & 0xff;
  target[offset + 3] = (value >>> 24) & 0xff;
}

function readU32Le(source: Uint8Array, offset: number): number {
  return (
    ((source[offset] ?? 0) |
      ((source[offset + 1] ?? 0) << 8) |
      ((source[offset + 2] ?? 0) << 16) |
      ((source[offset + 3] ?? 0) << 24)) >>>
    0
  );
}

/**
 * The 28 bytes this codec sends first.
 *
 * Hand-built, with no length prefix and no varints: a prelude that needed a decoder would be a
 * decoder running ahead of the gate that decides whether decoding is safe.
 */
export function encodeWirePrelude(abi: Readonly<WireAbi> = LOCAL_WIRE_ABI): Uint8Array {
  const out = new Uint8Array(WIRE_ABI_PRELUDE_LEN);
  out.set(WIRE_ABI_MAGIC, 0);
  writeAscii(out, 4, WIRE_ABI_FORK, 8);
  writeU32Le(out, 12, abi.abiEpoch);
  writeU32Le(out, 16, abi.protocolVersion);
  const fingerprint = fromHex(abi.schemaFingerprint);
  if (fingerprint.length !== 8) {
    throw new Error(`schema fingerprint must be 8 bytes, got ${fingerprint.length}`);
  }
  out.set(fingerprint, 20);
  return out;
}

/** True when `bytes` starts with the prelude magic. */
export function startsWithWireAbiMagic(bytes: Uint8Array): boolean {
  if (bytes.length < WIRE_ABI_MAGIC.length) {
    return false;
  }
  for (let index = 0; index < WIRE_ABI_MAGIC.length; index += 1) {
    if (bytes[index] !== WIRE_ABI_MAGIC[index]) {
      return false;
    }
  }
  return true;
}

/**
 * Parses a peer's prelude out of the first {@link WIRE_ABI_PRELUDE_LEN} bytes.
 *
 * Throws {@link AbiMismatchError} when the magic is absent, which is the *legacy* case: a
 * pre-prelude (or upstream) server. That is refused rather than fallen back on, because falling
 * back is precisely how a version-matching peer with a different tag table gets accepted.
 */
export function decodeWirePrelude(bytes: Uint8Array): WirePrelude {
  if (bytes.length < WIRE_ABI_PRELUDE_LEN) {
    throw new Error(
      `wire-ABI prelude needs ${WIRE_ABI_PRELUDE_LEN} bytes, got ${bytes.length}`,
    );
  }
  if (!startsWithWireAbiMagic(bytes)) {
    throw new AbiMismatchError(
      undefined,
      "the server sent no herdr-mx wire-ABI prelude, so its wire layout cannot be identified. " +
        "It is an older herdr (protocol <= 20) or a different fork; upstream/master and herdr-mx " +
        "both report PROTOCOL_VERSION 20 while disagreeing on ServerMessage::Terminal (13 here, " +
        "2 there), so guessing would mean a black screen instead of an error. Update herdr on the " +
        "remote.",
    );
  }
  return {
    fork: readAscii(bytes, 4, 8),
    abiEpoch: readU32Le(bytes, 12),
    protocolVersion: readU32Le(bytes, 16),
    schemaFingerprint: toHex(bytes.subarray(20, 28)),
  };
}

/** One line naming every axis of a peer's identity. */
export function describeWireAbi(abi: Readonly<WirePrelude | WireAbi>): string {
  const fork = "fork" in abi ? abi.fork : WIRE_ABI_FORK;
  return `fork=${fork} protocol=${abi.protocolVersion} abi_epoch=${abi.abiEpoch} schema=${abi.schemaFingerprint}`;
}

/**
 * Fails loudly unless the peer's announced ABI is one this codec can decode.
 *
 * Checked before a single `ServerMessage` byte is parsed, so a rejection means nothing of the
 * peer's stream was ever interpreted.
 */
export function assertPeerAbiAccepted(peer: WirePrelude): void {
  if (peer.fork !== WIRE_ABI_FORK) {
    throw new AbiMismatchError(
      peer,
      `peer speaks wire fork '${peer.fork}', this client speaks '${WIRE_ABI_FORK}'; they are ` +
        "different protocols that happen to share a version number",
    );
  }
  const accepted = ACCEPTED_WIRE_ABIS.some(
    (abi) =>
      abi.protocolVersion === peer.protocolVersion &&
      abi.abiEpoch === peer.abiEpoch &&
      abi.schemaFingerprint === peer.schemaFingerprint,
  );
  if (accepted) {
    return;
  }
  const axis =
    peer.protocolVersion !== LOCAL_WIRE_ABI.protocolVersion
      ? "protocol version"
      : peer.abiEpoch !== LOCAL_WIRE_ABI.abiEpoch
        ? "wire ABI epoch"
        : "wire schema fingerprint (same declared version and epoch, different byte layout)";
  throw new AbiMismatchError(
    peer,
    `incompatible ${axis}: peer ${describeWireAbi(peer)} vs this client ` +
      `${describeWireAbi(LOCAL_WIRE_ABI)}; update whichever side is older`,
  );
}
